# stage one, build the app 
FROM node:18-alpine as builder 

WORKDIR /app 

COPY  . .

RUN npm install 

RUN npm run build 

FROM node:18-bullseye-slim

WORKDIR /app 

COPY --from=builder /app/dist .
COPY --from=builder /app/package*.json /app/

RUN npm install --omit=dev

EXPOSE 5000

CMD [ "npm", "run", "start:prod" ]